# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: cURLUploader@2
  inputs:
    files: '**/*.jar'
    serviceEndpoint: 'azurechinablob'
    options: '-H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob"'
    authType: ServiceEndpoint
    remotePath: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Upload File to Blob
      curl -H "x-ms-blob-type: BlockBlob" --upload-file '/home/vsts/work/1/s/target/hello-0.0.1-SNAPSHOT.jar' --url "https://sgsfilesnew.blob.core.chinacloudapi.cn/devops/hello-0.0.1-SNAPSHOT.jar?$(SGS-BLOB-SAS-TOKEN)"